<!DOCTYPE html>
<html>
<head>
    <title>Statistic-info</title>
</head>
<body>
<div style="font-size: 12px; color: green; font-family: Arial,serif">[statistic-info.ftlh] :: started</div>
<hr>
    Дата
    Тираж
    Выпавшие числа<br>
    [${getStatisticById.timeNewPost}]
    ${getStatisticById.id}
    ${getStatisticById.tab_1}
    ${getStatisticById.tab_2}
    ${getStatisticById.tab_3}
    ${getStatisticById.tab_4}
    ${getStatisticById.tab_5}
    ${getStatisticById.tab_6}
    ${getStatisticById.tab_7}
    ${getStatisticById.tab_8}
<hr>
</body>
</html>